export const seedIdeas = [
  "Inbox Dojo: email triage that turns messy threads into action cards, receipts, and one merciful reply draft.",
  "What if abandoned shopping carts got a tiny financial therapy session before checkout?",
  "Charge tourists five bucks to rent a local's perfect two-hour walk, snack stops included.",
  "Turn noisy Zoom calls into a two-sentence decision log before everyone pretends alignment happened.",
  "Tiny museums need a donor CRM that also remembers artifacts, tour groups, and the volunteer named Marsha.",
  "Rent the good webcam from someone upstairs instead of buying another plastic rectangle.",
  "Street vendors text receipts to a bot; it builds sales charts, tax notes, and weather warnings.",
  "Office Plant Rescue: subscription plant care for lobbies where the ficus has seen things.",
  "Founder Penance: messy notes become investor updates, apology emails, and a roadmap with fewer lies.",
  "Coffee shops could run pastry drop subscriptions for regulars who fear missing the good croissant.",
  "Could landlords and tenants share one repair timeline with photos, appointment slots, and less emotional warfare?",
  "Spare commercial kitchens become bookable prep space for home chefs, caterers, and sauce people.",
  "Local restaurants share delivery drivers during slow hours instead of feeding the platform monster.",
  "Browser plugin idea: label SaaS pricing pages by how much psychological fog they contain.",
  "Voice memos from plumbers, electricians, and roofers become estimates, parts lists, and follow-up texts.",
  "Emergency business cards printed from airport kiosks for people who just remembered networking exists.",
  "The anti-meeting calendar protects deep work by creating boring fake holds nobody wants to join.",
  "Payroll Sidekick: a plain-language payroll helper for tiny businesses with one manager and twelve tabs open.",
  "Let farmers market sellers split one bookkeeper who understands cash, Square, and seasonal chaos.",
  "Borrow fancy table settings from neighbors instead of buying plates for one dinner party and a lifetime of guilt.",
  "Saturday Tool Library: deposits, repair logs, and reminders to return the cursed tile saw.",
  "Laundry Night Cafe puts espresso, snacks, and a kids corner beside apartment-building washers.",
  "The apartment freezer exchange lets soup maximalists rent space from people with suspiciously empty drawers.",
  "Bring DMV paperwork help to apartment lobbies, senior centers, and coworking spaces once a month.",
  "Kids toys should rotate like library books before every living room becomes a plastic asteroid field.",
  "Forgotten lunch? Gym shoes? Violin? Local courier hops between schools, offices, and homes.",
  "Cosplay ER: quick repairs for costumes, theater props, school projects, and cardboard with emotional value.",
  "Retiree downsizing concierge matches furniture to neighbors before estate-sale panic mode begins.",
  "Pop-up product photo van gives tiny shops clean catalog photos in one afternoon.",
  "Trash Room Spa: recurring pressure washing for apartment buildings before civilization gives up.",
  "Reserve public picnic tables with a cleanup deposit and a shame-free cancellation button.",
  "Ugly produce club pairs tiny farms with recipes, harvest gossip, and discounted weekly boxes.",
  "Thrift Scout learns your sizes and tolerance for cursed patterns, then alerts you from nearby stores.",
  "Turn church halls and library rooms into rural coworking spots with day passes and quiet rules.",
  "Garage Shelf Network rents short-term storage in basements, garages, and empty retail back rooms.",
  "Bulk-buy pantry basics by apartment building so nobody has to individually panic-order paper towels.",
  "Quiet Places Map ranks public spots by outlets, bathrooms, seating, and social expectations.",
  "Espresso Rescue subscription maintains home machines before they become countertop sculpture.",
  "Food truck paperwork navigator tracks permits, fire inspections, and cities with forms from 1997.",
  "Old family photos become tagged archives with audio stories before everyone forgets who Uncle Ray was.",
  "Gallery Roulette lets emerging artists sell unfinished work while buyers vote on the next strange constraint.",
  "Seven-minute podcasts only: one tight story, one useful recommendation, no rambling victory lap.",
  "Readers vote on the next comic panel, artists get paid per branch, chaos becomes canon.",
  "Mural Preview lets artists test designs on real wall photos with city permit reminders.",
  "License tiny ambient soundscapes from indie musicians to cafes, games, dentists, and haunted elevators.",
  "Poetry vending machine: enter a place, mood, and questionable life decision; receive a custom poem.",
  "Rebuild destroyed, stolen, censored, or rumored art as a VR museum with source notes.",
  "One-minute documentary festival about ordinary jobs nobody understands until the close-up.",
  "Public-domain novels become stage scripts for school drama clubs with costumes rated by budget pain.",
  "Fans sponsor one absurd monthly constraint for an artist and get the making-of notes.",
  "Blank walls become neighborhood projection nights for local animation, film scraps, and digital murals.",
  "Album-cover swap connects bands with illustrators who can make the EP look less like a folder icon.",
  "Adaptive music packs for indie games that cannot afford a composer living inside the engine.",
  "Photo booth pitch: print people as fake historical oil paintings with scandal captions.",
  "Dance prompts for weddings, schools, and flash mobs from choreographers who sell eight-count packs.",
  "Art teachers upload their actual closet supplies; the app creates projects from glue, yarn, and hope.",
  "Mail micro-sculpture kits designed by emerging artists to people with tiny desks and big ambition.",
  "Local businesses rent rotating neighborhood art instead of buying one beige print forever.",
  "Failed lab images sold as prints to fund the next beautiful scientific failure.",
  "Bike-mounted heat sensors map city heat islands block by block for schools and planners.",
  "Compost Mood Ring tells you whether the pile is thriving, too dry, or entering villain mode.",
  "Lab notebooks without tears: messy bench notes become clean protocols and failure confessions.",
  "Unused university lab time becomes bookable off-hours space for startups and independent researchers.",
  "Retired engineers coach science fair projects that do not explode indoors.",
  "Phone microscope missions guide classrooms through pond water, kitchen crystals, and backyard biology.",
  "Weather forecasts translated into farmers market risk: wind, heat, spoilage, and booth survival.",
  "Pipette wrists deserve a warning wearable before repetitive strain ruins lab life.",
  "Patient advocacy groups pitch real-world research questions to scientists looking for useful problems.",
  "Kitchen-safe chemistry kits teach dyes, materials, and reactions without turning the sink into court evidence.",
  "Drones map invasive vines for parks departments before the plants annex the playground.",
  "Research papers become comic-strip summaries for donors, patients, and exhausted grad students.",
  "Fishing co-ops need a water temperature and algae dashboard that does not require a PhD.",
  "Retired scientists peer-review startup claims for founders brave enough to invite the red pen.",
  "Family emergency plans built from local flood, fire, heat, pets, meds, and stubborn relatives.",
  "Kids vote on aquarium enrichment puzzles, then watch animals test the winning designs.",
  "Borrowable school science equipment so every classroom does not buy one lonely spectrometer.",
  "Mushroom packaging grown near warehouses and sold to shippers who want less foam shame.",
  "Pollinator cameras count garden visits and tell neighborhoods which flowers are pulling their weight.",
  "Sidewalk Crack League turns citizen science into a game cities can use for repair triage.",
  "Furniture rescue mutual aid matches donated couches with families moving after emergencies.",
  "Time-bank credits for tutoring, dog walking, repairs, rides, and other neighborhood favors.",
  "Tenants document maintenance issues together and send polite but relentless building requests.",
  "Community fridge inventory with volunteer shifts and alerts when the mystery casserole joined society.",
  "Rural medical rides coordinated through vetted volunteers, backup drivers, and appointment reminders.",
  "Retirees teach short paid workshops on sewing, taxes, repairs, cooking, and bureaucratic survival.",
  "Microdonations route five dollars a month to hyperlocal projects with receipts and progress photos.",
  "Disaster prep drills scheduled like community events instead of grim homework.",
  "Childcare swap circles for parents with uneven work hours and verified neighborhood trust.",
  "Garden Plot Treaty manages water schedules, harvest shares, waiting lists, and tomato diplomacy.",
  "Adopt-a-bench sponsors repairs and adds tiny resident audio stories to public seating.",
  "Mutual-aid groups verify needs without making people perform hardship for strangers.",
  "Libraries could host repair cafes, skill nights, tiny civic debates, and tool checkouts from one dashboard.",
  "Neighborhood newsletter co-op shares ad sales, printing, editing tools, and boring legal templates.",
  "Empty storefronts become rotating classrooms for cooking, language, repair, and art workshops.",
  "Walking groups planned around shade, benches, bathrooms, gentle hills, and gossip density.",
  "Pantry stock predictor estimates what staples run low after storms, benefit dates, and school breaks.",
  "School pickup circles match trusted families before everyone misses each other by four chaotic minutes.",
  "Flyer translator turns community event posters into the top languages on the block.",
  "Block microgrants let residents pitch one-block improvements and vote with tiny budgets.",
  "Ballot measures explained as recipes: ingredients, tradeoffs, substitutions, and likely mess.",
  "Ninety-second candidate answers, same questions for everyone, no soft-focus flag montage.",
  "Public-comment drafting help turns resident concerns into clear testimony without consultant sludge.",
  "Promise Tracker watches campaign promises after election day and pings missed deadlines.",
  "Compare local candidates by actual policy actions, not yard sign typography.",
  "Town hall livestreams with live summaries, searchable clips, and jargon panic buttons.",
  "City budget simulator lets residents move fake money around and watch fictional consequences complain.",
  "Election reminders for local races, registration deadlines, polling place changes, and ballot curing.",
  "Match volunteers to local government boards that currently have three members and a fax machine.",
  "Public-records request assistant writes narrow, polite asks and tracks agency response clocks.",
  "Fundraising-email decoder labels political blasts by emotional manipulation flavor.",
  "School board agenda previews in plain English for parents with ten minutes and low patience.",
  "Citizens sponsor local journalism questions and vote on what reporters investigate next.",
  "Map hostile sidewalks, bus stops, and crossings for wheelchair users, stroller pushers, and tired knees.",
  "Rumor control hotline answers local misinformation with sourced, boring, blessedly specific facts.",
  "One-pothole coalitions form temporary groups around one bus route, curb cut, or sidewalk crater.",
  "Zoning simulator lets users tweak density, transit, and taxes while fictional neighbors object.",
  "Canvass scheduler for advocacy groups who keep losing volunteers inside spreadsheet tunnels.",
  "City service response dashboard shows which tickets move fast and which entered the fog.",
  "Legislative bills as sports box scores: sponsors, amendments, fiscal hits, and plain-language stakes.",
  "Rec league command center handles payments, subs, standings, field changes, and fewer group texts.",
  "Rent backyard batting cages, pickleball courts, garage gyms, and lonely rebound nets by the hour.",
  "Fantasy sports points for assists, sportsmanship, hustle, and wholesome teamwork instead of only stars.",
  "Phone video coaching turns youth practice clips into three simple drills and one parent-safe note.",
  "Pickup game finder ranks games by intensity, friendliness, and chance someone brings cones.",
  "Retired athletes host tiny clinics in parks, school gyms, and driveways with delusions of greatness.",
  "Tournament recovery kits ship electrolyte packets, tape, snacks, and dignity after weekend heroics.",
  "Wearable scoreboard for informal games where nobody remembers whether it is 9-7 or 11-6.",
  "Parent-recorded youth games become shareable highlight clips without needing a broadcast truck.",
  "Used sports gear marketplace verifies size, condition, and whether the smell has legal standing.",
  "Gym class remix: circus skills, parkour basics, dance battles, and cooperative games for non-jocks.",
  "Running routes built around murals, bakeries, water fountains, bathrooms, and dramatic hills.",
  "Practice-slot exchange sells unused small-venue time to teams at the last minute.",
  "Referee training simulator teaches conflict de-escalation through increasingly ridiculous parents.",
  "Adaptive sports groups share equipment, venue notes, guides, and volunteer availability.",
  "Office wellness leaderboard rewards consistency, lunch walks, and not turning health into suffering.",
  "Bike commute league scores safety, weather bravery, repair skills, and excellent bell usage.",
  "Youth sports carpool planner with field-change alerts and emergency snack assignments.",
  "Adults learn sports they were too embarrassed to try as kids through private micro-lessons.",
  "Minor league fan club app rewards attendance streaks, chants, mascot lore, and concession bravery.",
  "Could amateur teams get useful analytics from one shaky sideline video and a patient volunteer?",
  "Match social movements with lawyers, designers, translators, bookkeepers, and spreadsheet adults.",
  "Campaign policy changelogs show every platform change like software release notes.",
  "Mutual-aid translation hotline routes urgent flyers and forms to trusted local translators.",
  "Protest supply library lends megaphones, safety vests, folding tables, clipboards, and calm signage.",
  "Civic rewards for reporting broken infrastructure, attending boring meetings, and closing the loop.",
  "Neighborhood emergency radio club with simple kits, monthly drills, and zero bunker energy.",
  "Resident Assembly Kit: agendas, facilitation cards, childcare checklist, snacks budget, and voting tools.",
  "Grant reports become reusable donor stories for nonprofits that cannot write the same paragraph again.",
  "Volunteer vibe matching pairs nonprofits with people who want spreadsheets, door knocking, or soup logistics.",
  "Union meeting childcare pool so parents can organize without bribing teenagers at the last second.",
  "Cofounder dating where the first match question is how you behave during a server outage.",
  "Fake rejection letters by subscription to build founder emotional calluses before fundraising.",
  "Rent one deeply specific costume piece for themed parties, spirit days, and suspicious office events.",
  "Name my houseplant, write its origin myth, and send weekly care threats.",
  "Leftover archaeology magnet judges fridge containers before they become a discovery channel special.",
  "Micro-consulting for people weirdly good at one tiny life task, from packing cubes to fish tanks.",
  "Travel plans built around bathrooms, quiet benches, snack reliability, and avoiding airport sprinting.",
  "Lock distracting apps until you describe the actual task without saying strategy.",
  "Remote teams receive tiny weekly rituals that do not require forced vulnerability or matching hoodies.",
  "Apology writers for roommates, group chats, neighbors, and accidental reply-all incidents.",
  "LinkedIn detox removes motivational fog, fake thought leadership, and business cosplay from profiles.",
  "Alarm clock voice assistant negotiates wake-up time like a tired labor union.",
  "Recipes based only on what is about to become emotionally unstable in your fridge.",
  "Family group chat plans become calendars, carpools, and fewer wounded feelings.",
  "Screenshot archive for things that felt important at 1:12 AM and now need a reason to exist.",
  "Tiny insurance for lent books: get the book back, get paid, or receive ceremonial closure.",
  "Museum labels for objects in your house so cleaning feels historic and slightly judgmental.",
  "Cable Finder turns home organization into a game before you buy another doomed cable.",
  "Strangers vote on which unfinished hobby you are legally allowed to abandon.",
  "Backyard climate upgrades bundled by neighborhood: shade sails, rain barrels, native plants, and costs.",
  "Restaurant rush predictor combines weather, school calendars, local events, and rival taco diplomacy.",
  "Private baby-photo sharing where relatives pass a tiny etiquette quiz before commenting.",
  "Small business insurance translated into disaster scenarios starring your actual shop.",
  "Repair appointments with photo proof, shared notes, and fewer passive-aggressive texts.",
  "Crop Story Club helps tiny farms sell weekly boxes with recipes, field notes, and ugly vegetable fame.",
  "Indie bookstores run preorder clubs for books too strange for bestseller math.",
  "Apartment restaurants and corner stores trade leftover ingredients before closing.",
  "Curiosity walks led by local experts in architecture, birds, ghosts, labor history, or snacks.",
  "Co-parent logistics that keeps schedules boring, factual, and legally calm.",
  "Small clinics send plain-language follow-up instructions in multiple languages by text.",
  "Office buildings auction unused evening meeting rooms to tutors, coaches, and therapists.",
  "Short videos only for failed projects, what broke, and what the team learned before the music swells.",
  "Local historians fact-check house histories, ghost tours, suspicious plaques, and neighborhood legends.",
  "Chaotic WhatsApp voice notes become a family plan everyone can survive.",
  "Native seed swap with location notes, bloom times, and pollinator sightings.",
  "Vacant lots turn into temporary sports courts by day and art markets by evening.",
  "Founder support group where every pitch gets one angel note, one devil note, and one practical errand.",
  "Climate adaptation planner for neighborhood associations with costs, volunteer roles, and dramatic before photos.",
  "Rent unusual musical instruments from people who bought them during ambitious phases.",
  "Scientists auction naming rights for lab equipment to fund tiny experiments.",
  "Night Market OS helps pop-up vendors handle permits, shared power, stall maps, and rain plans.",
  "Bus-stop book clubs: QR codes, tiny lending shelves, and neighborhood reading missions.",
  "Permit Palooza bundles forms, deadlines, and inspector notes for block parties and small festivals.",
  "What if every vacant office lobby hosted rotating lunch-hour science demos?",
  "Tiny Farm Dispatch sells harvest texts from local growers to restaurants needing last-minute specials.",
  "Sports parents trade verified snack runs, rain alerts, and field directions in one calm channel.",
  "Repair Cafe Passport rewards people for fixing lamps, jackets, chairs, and dignity across town.",
  "Policy Karaoke turns dense city proposals into call-and-response scripts for community meetings.",
  "Studio Shareboard matches photographers, ceramicists, dancers, and podcasters with odd-hour creative space.",
  "Moonshot Homework Club pairs ambitious kids with retired scientists for wildly practical project advice."
];

export const seedCommentAuthors = [
  "Anonymous founder",
  "Purgatory lurker",
  "Overcaffeinated angel",
  "Friendly skeptic",
  "Market realist",
  "Chaos intern",
  "Weekend operator",
  "Spreadsheet adult",
  "Tiny checks investor",
  "Launch party heckler",
  "Neighborhood strategist",
  "Recovering product manager"
];

export const seedVoterPoolSize = 400;
